services:
  # 1. La Base de Donn√©es (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: pounce_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: pounce
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. L'interface d'administration (PgAdmin)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pounce_admin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pounce.com
      PGADMIN_DEFAULT_PASSWORD: password123
    ports:
      - '5050:80'
    depends_on:
      - db

volumes:
  postgres_data:
